magazine/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'sessions#new'
  get  '/signup',  to: 'users#new'

  resources :users

  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :articles
end

magazine/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

magazine/app/models/article.rb
class Article < ApplicationRecord
	# Tagging and Sub tagging handled by a single table inheritance
	# tagging kept polymorphic so that it can be used to tag other objects if required
	has_many :taggings, -> { where(category: '1') },
				as: :taggable
	has_many :tags, -> { distinct }, through: :taggings
	has_many :sub_taggings, -> { where(category: '0') },
				as: :taggable, class_name: 'Tagging'
	has_many :sub_tags, -> { distinct }, through: :sub_taggings, class_name: 'Tag',
				source: :tag


	belongs_to :user

	default_scope -> { order(created_at: :desc) }

	validates :description, presence: true
	validates :title, presence: true, length: { minimum: 5 }

	attr_accessor :tag_list, :sub_tag_list

	# Gives the name of owner of the article
	def owner_name
		user.name
	end

	# search method which will search in taggings/sub taggings/ title/ content of articles
	def self.search keyword
		# below statement results in single query to search at all possible places
		(keyword_in_title_or_text(keyword) + keyword_in_tags_or_sub_tags(keyword)).uniq
	end

	# this method returns tag list of article
	def tag_list
	 	tags.map(&:name).join(", ")
	end

  	# this method assigns tags to articles
  	def tag_list=(names)
    	self.tags = names.split(",").map do |n|
      		Tag.where(name: n.strip).first_or_create!
    	end
  	end

  	# this method returns sub tag list of article
  	def sub_tag_list
  		sub_tags.map(&:name).join(", ")
  	end

  	# this method assigns sub tags to articles
  	def sub_tag_list=(names)
    	self.sub_tags = names.split(",").map do |n|
      		Tag.where(name: n.strip).first_or_create!
    	end
  	end

  	private

  	# queries for keyword in article title or description
  	# forcing eager load since we're looping over all the articles in view
  	# this prevents N+1 query problem
  	def self.keyword_in_title_or_text keyword
  		Article.eager_load([:tags, :sub_tags, :taggings]).where(
  			"title ILIKE ? OR description ILIKE ?","%#{keyword}%", "%#{keyword}%"
  		)
  	end

	# queries for keyword in tags or sub_tags (both from single table only)
	# forcing eager load since we're looping over all the articles in view
  	# this prevents N+1 query problem
  	def self.keyword_in_tags_or_sub_tags keyword
  		Article.eager_load([:tags, :sub_tags, :taggings]).where(
			"tags.name ILIKE ?", "%#{keyword}%"
			).references(:tags)
  	end
end

magazine/app/models/tag.rb
class Tag < ApplicationRecord
	has_many :articles, through: :taggings, source: :taggable,
				source_type: "Article"
	has_many :sub_tagged_article, through: :taggings, source: :taggable,
				source_type: "Article_sub_tag", class_name: "Article"
end

magazine/app/models/tagging.rb
class Tagging < ApplicationRecord
	belongs_to :tag
	belongs_to :taggable, polymorphic: true
end

magazine/app/models/user.rb
class User < ApplicationRecord
	has_many :articles
	before_save { self.email = email.downcase }
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
					  format: { with: VALID_EMAIL_REGEX },
					  uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }
end

magazine/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :set_cache_headers
  include SessionsHelper

  private

  # to prevent caching of page by browsers
  def set_cache_headers
    response.headers["Cache-Control"] = "no-cache, no-store"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
end

magazine/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	# a user must be logged in before accessing articles
	before_action :authenticate_user

	def create
		@article = Article.new(article_params.merge(:user_id => current_user.id))

		if @article.save
			# save article's tags and sub tags only after the article is saved successfully
			@article.tag_list = params[:article][:tag_list]
			@article.sub_tag_list = params[:article][:sub_tag_list]
			redirect_to @article
		else
			render 'new'
		end
	end

	def new
		@article = Article.new
	end

	def show
  		@article = Article.find(params[:id])
  	end

  	def index
  		@home_page = true
  		@articles = if params[:lookup]
  			Article.search(params[:lookup])
  		else
  			# To avoid N+1 query problem in view, eager_loading is used instead of joins
			@article = Article.eager_load([:tags, :sub_tags, :taggings])
		end
  	end

  	def edit
  		@article = Article.find(params[:id])
  	end

  	def update
  		@article = Article.find(params[:id])
 		if @article.update(article_params)
 			# update tag list and sub tag list if article is updated
 			@article.tag_list = params[:article][:tag_list]
 			@article.sub_tag_list = params[:article][:sub_tag_list]
	    	redirect_to @article
	  	else
	    	render 'edit'
	  	end
  	end

  	private

	def article_params
    	params.require(:article).permit(:title, :description, :lookup)
	end

end

magazine/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
	    if user && user.authenticate(params[:session][:password])
	      log_in user
	      redirect_to user
	    else
	      flash.now[:danger] = 'Invalid email or password'
	      render 'new'
	    end
	end

	def destroy
		log_out
		redirect_to login_path
	end

end

magazine/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
	    if @user.save
	    	log_in @user
      		flash[:success] = "Welcome to the Homify Magazine!"
	    	redirect_to @user
	    else
	      render 'new'
	  	end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
	end
end

magazine/app/helpers/application_helper.rb
module ApplicationHelper
end

magazine/app/helpers/articles_helper.rb
module ArticlesHelper
end

magazine/app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in user
      session[:user_id] = user.id
    end

    # returns the current user
    def current_user
      @current_user ||= User.find_by(id: session[:user_id])
    end

    #  checks if a user is logged in or not
    def logged_in?
      !current_user.nil?
    end

    # log out of account
    def log_out
      session.delete(:user_id)
      @current_user = nil
    end

    # authentication of user
    def authenticate_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

magazine/app/helpers/users_helper.rb
module UsersHelper
end

magazine/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>

  <div class="field">
    <%= f.label :sub_tag_list, "Sub Tags (separated by commas)" %><br />
    <%= f.text_field :sub_tag_list %>
  </div>

  <p>
    <%= f.submit %>
  </p>

<% end %>

magazine/app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

magazine/app/views/articles/index.html.erb
<h1>Articles</h1>

<div id="articles">

  <%= form_tag(articles_path, method: :get) do %>
    <%= text_field_tag :lookup, params[:lookup] %>
    <%= submit_tag 'Search (By Tag/Sub Tag/Title/Contents)' %>
  <% end %>

  <% @articles.each do |article| %>
    <h2>Click to view article: <%= link_to article.title, article %></h2>
    <p>Created On: <%= article.created_at %></p>
    <p>Contents: <%= article.description %></p>
    <p>Tags: <%= article.tag_list %></p>
    <p>Sub Tags: <%= article.sub_tag_list %></p>
    <p><%= link_to "Edit Article", edit_article_path(article) %></p>
  <% end %>
</div>

magazine/app/views/articles/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', articles_path %>

magazine/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<p>
  <strong>Tag List:</strong>
  <%= @article.tag_list %>
</p>

<p>
  <strong>Sub Tag List:</strong>
  <%= @article.sub_tag_list %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @article.owner_name %>
</p>

<%= link_to 'Back', articles_path %>
<td><%= link_to 'Edit', edit_article_path(@article) %></td>

magazine/app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

magazine/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Homify Magazine", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li><%= link_to "Create Article",   new_article_path %></li>
              <li><%= link_to "View All Articles",   articles_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <!-- <li><%= link_to "Log in", login_path %></li> -->
            <% end %>
          </ul>
        </nav>
      </div>
</header>

magazine/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Magazine</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= @home_page ? 'homepage' : ''%>">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

magazine/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

magazine/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Retype Password" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

magazine/app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>